### ISSUE TITLE
Site Internet ?

### ISSUE THREAD

**Issue by Fourchaux** [engboris/mappagani#1]
Juste une petite question : 
est-ce-qu'il existe un site Internet pour ce cours L3 ?

**Comment by engboris** [comment]
Bonjour,

Non pas vraiment. Les ressources du cours sont hébergées sur la plateforme Moodle interne à l'université.
(Comment êtes vous arrivé ici ?)

**Comment by Fourchaux** [comment]
Ah, dommage :=(  

Ici ? recherche basique - juste 'ocaml' - sur (les Repositories) Github. 
(avec Sort:Recently Updated -> résultat en page 2, aujourd'hui)

**Comment by engboris** [comment]
Ok.

Sinon comme alternative il y a le MOOC OCaml de l'Université Paris 7 (Diderot) : 
https://www.fun-mooc.fr/courses/parisdiderot/56002S02/session02/about

**Comment by Fourchaux** [comment]
Yep, les MOOCs (enfin le MOOC_1 surtout, le MOOC_2 est exactement le même) m'occupent bien !

Vos enseignants travaillent sur ce MOOC OCaml ?

**Comment by engboris** [comment]
Les enseignants sont dans mon université mais ce ne sont pas mes enseignants directs.
